project_name: 'librespeed-go'

builds:
  - env:
      - CGO_ENABLED=0

nfpms:
  - homepage:  https://freedom.nl
    description: LibreSpeed-Go backend
    maintainer: Freedom Internet DevOps <systeembeheer@freedomnet.nl>
    license: LGPL 3.0
    vendor: Freedom Internet
    contents:
      - src: scripts/defaults
        dst: /etc/default/librespeed-go
      - src: scripts/systemd/librespeed-go.service
        dst: /usr/lib/systemd/system/librespeed-go.service
      - src: web/assets
        dst: /usr/local/share/librespeed-go/assets
      - src: scripts/settings.toml
        dst: /etc/librespeed-go/settings.toml
        type: config
    formats:
      - deb
      - rpm
    dependencies:
      - systemd
    scripts:
        postinstall: scripts/postinstall.sh

archives:
  - files:
      - README.md
      - LICENSE
      - settings.toml
